"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2025-01-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create employees table first (no dependencies)
    op.create_table('employees',
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('joining_date', sa.Date(), nullable=False),
        sa.Column('designation', sa.String(length=100), nullable=True),
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='userrole'), nullable=False),
        sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ),
        sa.PrimaryKeyConstraint('employee_id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    
    # Create departments table (now employees table exists)
    op.create_table('departments',
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.Column('department_name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('head_of_department', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['head_of_department'], ['employees.employee_id'], ),
        sa.PrimaryKeyConstraint('department_id'),
        sa.UniqueConstraint('department_name')
    )
    op.create_index(op.f('ix_departments_department_id'), 'departments', ['department_id'], unique=False)
    
    # Add department_id foreign key constraint to employees table
    op.create_foreign_key('fk_employees_department', 'employees', 'departments', ['department_id'], ['department_id'])
    
    # Create leave_types table
    op.create_table('leave_types',
        sa.Column('leave_type_id', sa.Integer(), nullable=False),
        sa.Column('type_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('max_days_per_year', sa.Integer(), nullable=True),
        sa.Column('requires_approval', sa.Boolean(), nullable=True),
        sa.Column('is_paid', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('leave_type_id'),
        sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_leave_types_leave_type_id'), 'leave_types', ['leave_type_id'], unique=False)
    
    # Create rave_categories table
    op.create_table('rave_categories',
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('category_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('icon', sa.String(length=100), nullable=True),
        sa.Column('color', sa.String(length=7), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('category_id'),
        sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_rave_categories_category_id'), 'rave_categories', ['category_id'], unique=False)
    
    # Create attendance table
    op.create_table('attendance',
        sa.Column('attendance_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('attendance_date', sa.Date(), nullable=False),
        sa.Column('clock_in_time', sa.Time(), nullable=True),
        sa.Column('clock_out_time', sa.Time(), nullable=True),
        sa.Column('hours_worked', sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'ON_LEAVE', name='attendancestatus'), nullable=False),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
        sa.PrimaryKeyConstraint('attendance_id'),
        sa.UniqueConstraint('employee_id', 'attendance_date', name='unique_employee_date')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_attendance_id'), 'attendance', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    
    # Create holidays table
    op.create_table('holidays',
        sa.Column('holiday_id', sa.Integer(), nullable=False),
        sa.Column('holiday_name', sa.String(length=100), nullable=False),
        sa.Column('holiday_date', sa.Date(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_optional', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('holiday_id'),
        sa.UniqueConstraint('holiday_date')
    )
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_holidays_holiday_id'), 'holidays', ['holiday_id'], unique=False)
    
    # Create leave_balance table
    op.create_table('leave_balance',
        sa.Column('balance_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('leave_type_id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('total_allocated', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('used_days', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('remaining_days', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
        sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.leave_type_id'], ),
        sa.PrimaryKeyConstraint('balance_id'),
        sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='unique_employee_leave_year')
    )
    op.create_index(op.f('ix_leave_balance_balance_id'), 'leave_balance', ['balance_id'], unique=False)
    op.create_index(op.f('ix_leave_balance_employee_id'), 'leave_balance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balance_year'), 'leave_balance', ['year'], unique=False)
    
    # Create leave_applications table
    op.create_table('leave_applications',
        sa.Column('leave_application_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('leave_type_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('total_days', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('applied_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('approved_rejected_on', sa.DateTime(timezone=True), nullable=True),
        sa.Column('rejection_reason', sa.Text(), nullable=True),
        sa.Column('attachments', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['employees.employee_id'], ),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
        sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.leave_type_id'], ),
        sa.PrimaryKeyConstraint('leave_application_id')
    )
    op.create_index(op.f('ix_leave_applications_employee_id'), 'leave_applications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_applications_leave_application_id'), 'leave_applications', ['leave_application_id'], unique=False)
    op.create_index(op.f('ix_leave_applications_status'), 'leave_applications', ['status'], unique=False)
    
    # Create notifications table
    op.create_table('notifications',
        sa.Column('notification_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('type', sa.Enum('GENERAL', 'LEAVE', 'ATTENDANCE', 'RAVE', 'SYSTEM', name='notificationtype'), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('link', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
        sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    
    # Create raves table
    op.create_table('raves',
        sa.Column('rave_id', sa.Integer(), nullable=False),
        sa.Column('from_employee_id', sa.Integer(), nullable=False),
        sa.Column('to_employee_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_anonymous', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['rave_categories.category_id'], ),
        sa.ForeignKeyConstraint(['from_employee_id'], ['employees.employee_id'], ),
        sa.ForeignKeyConstraint(['to_employee_id'], ['employees.employee_id'], ),
        sa.PrimaryKeyConstraint('rave_id')
    )
    op.create_index(op.f('ix_raves_from_employee_id'), 'raves', ['from_employee_id'], unique=False)
    op.create_index(op.f('ix_raves_rave_id'), 'raves', ['rave_id'], unique=False)
    op.create_index(op.f('ix_raves_to_employee_id'), 'raves', ['to_employee_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint first
    op.drop_constraint('fk_employees_department', 'employees', type_='foreignkey')
    
    op.drop_index(op.f('ix_raves_to_employee_id'), table_name='raves')
    op.drop_index(op.f('ix_raves_rave_id'), table_name='raves')
    op.drop_index(op.f('ix_raves_from_employee_id'), table_name='raves')
    op.drop_table('raves')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_leave_applications_status'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_leave_application_id'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_employee_id'), table_name='leave_applications')
    op.drop_table('leave_applications')
    op.drop_index(op.f('ix_leave_balance_year'), table_name='leave_balance')
    op.drop_index(op.f('ix_leave_balance_employee_id'), table_name='leave_balance')
    op.drop_index(op.f('ix_leave_balance_balance_id'), table_name='leave_balance')
    op.drop_table('leave_balance')
    op.drop_index(op.f('ix_holidays_holiday_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_rave_categories_category_id'), table_name='rave_categories')
    op.drop_table('rave_categories')
    op.drop_index(op.f('ix_leave_types_leave_type_id'), table_name='leave_types')
    op.drop_table('leave_types')
    
    # Drop departments table first (has foreign key to employees)
    op.drop_index(op.f('ix_departments_department_id'), table_name='departments')
    op.drop_table('departments')
    
    # Drop employees table last
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###